- hosts: localhost
  tasks:
    - name: Building Maven Project 
      shell: mvn install

- hosts: vagrant_node
  become: yes
  tasks:
    - name: Copying jar to node
      import_role:
        name: copy_jar_to_node
      vars:
         jar_file_path: target/my-app-1.0.jar
    - name: Executing jar file
      import_role:
        name: execute_jar_file

